### ISSUE TITLE
Forge complains about missing DIBBLER_INSTALL_DIR and aborts

### ISSUE THREAD

**Issue by tomaszmrugalski** [isc-projects/forge#21]
After sidestepping issue #20, I encountered another one:

``` python
# ./run_test.py -6 -n v6.client.classification.onesubnet.docsis3.advertise.success
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "./run_test.py", line 216, in <module>
    failed = start_all(base_path, verbosity, scenario, tag, enable_xunit)
  File "./run_test.py", line 203, in start_all
    result = runner.run()  # start lettuce
  File "/usr/local/lib/python2.7/dist-packages/lettuce/__init__.py", line 137, in run
    self.loader.find_and_load_step_definitions()
  File "/usr/local/lib/python2.7/dist-packages/lettuce/fs.py", line 60, in find_and_load_step_definitions
    reload(module)  # always take fresh meat :)
  File "/home/thomson/devel/forge/lettuce/features/softwaresupport/dibbler_client/functions.py", line 5, in <module>
    from init_all import DIBBLER_INSTALL_DIR, IFACE
ImportError: cannot import name DIBBLER_INSTALL_DIR
#
```

It seems that init_all.py-default requires an update.

Fix: Adding DIBBLER_INSTALL_DIR="" solved the issue.

**Comment by tomaszmrugalski** [comment]
No longer an issue. Nobody cares about Dibbler anymore.
